### ISSUE TITLE
Add the [time] settings to config file and propagate to NetCDF output

### ISSUE THREAD

**Issue by kwilcox** [axiomalaska/modflow2netcdf#3]
New config file will look like so

```ini
[general]
precision: double

[space]
crs:      4269
origin_x: -105.243933
origin_y: 40.47377
rotation: 0
units:    ft

[time]
units:    days
base:     1970-01-01

```

**Comment by langevin-usgs** [comment]
Kyle, we should allow for hours, minutes, seconds (plus decimal seconds?),
in the base date.













*Christian LangevinResearch HydrologistOffice of GroundwaterU.S. Geological
Survey411 National CenterReston, VA 20192Office: 703-648-4169Fax:
703-648-6693Email: langevin@usgs.gov
<langevin@usgs.gov>https://profile.usgs.gov/langevin
<https://profile.usgs.gov/langevin>*

**Comment by kwilcox** [comment]
Anything that is easily parsable can be put into the config option.  These all work:

1970-01-01
1970-01-01T00:00:00.753 +0400
1970-01-01T00:00 -0500
